[package]
name = "grpc-contracts"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
generated = []

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
common = { path = "../common" }

[build-dependencies]
tonic-build = { workspace = true }
